### ISSUE TITLE
Suggest to "open" compiler range

### ISSUE THREAD

**Issue by 0xdcota** [yearn/tokenized-strategy#90]
Given that the contracts here, in particular the `BaseStrategy.sol` is an abstract contract meant to be inherited by many strategy implementations it will be helpful to make it more open in terms of compiler range? 

https://github.com/yearn/tokenized-strategy/blob/b2ad48b34ef762778e4a49c8942a9910612c9cf9/src/BaseStrategy.sol#L2

This in order to allow foundry to inherit it as a library working with other non-yearn libraries.

**Comment by Schlagonia** [comment]
fixed with newest tag https://github.com/yearn/tokenized-strategy/releases/tag/v3.0.2-1
